// zod schema → Swift Codable 模型。协议唯一真源是 src/models.ts;
// Swift 端禁止手工镜像,改协议后跑 `pnpm codegen:swift` 重新生成。

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import {
  BrowserControl,
  Device,
  Session,
  SessionFocus,
  Workspace,
  WorkspaceGroup,
} from "../src/models.ts";

const models: Record<string, z.ZodType> = {
  Device,
  Workspace,
  WorkspaceGroup,
  Session,
  SessionFocus,
  BrowserControl,
};

type JsonSchema = {
  type?: string | string[];
  anyOf?: JsonSchema[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
};

const jsonSchemas = Object.fromEntries(
  Object.entries(models).map(([name, schema]) => {
    const json = z.toJSONSchema(schema) as JsonSchema & { $schema?: string };
    delete json.$schema; // 顶层多出的 $schema 会破坏与内联 schema 的等价比较
    return [name, json as JsonSchema];
  }),
);

// 内联的 object schema 若与某个具名模型完全一致,引用该模型名
function namedModel(schema: JsonSchema): string | null {
  const key = JSON.stringify(schema);
  for (const [name, candidate] of Object.entries(jsonSchemas)) {
    if (JSON.stringify(candidate) === key) return name;
  }
  return null;
}

function swiftType(schema: JsonSchema, context: string): string {
  if (schema.anyOf) {
    const nonNull = schema.anyOf.filter((s) => s.type !== "null");
    if (nonNull.length !== 1 || nonNull.length === schema.anyOf.length) {
      throw new Error(`unsupported anyOf at ${context}`);
    }
    return `${swiftType(nonNull[0]!, context)}?`;
  }
  if (Array.isArray(schema.type)) {
    const nonNull = schema.type.filter((t) => t !== "null");
    if (nonNull.length !== 1 || nonNull.length === schema.type.length) {
      throw new Error(`unsupported type union at ${context}`);
    }
    return `${swiftType({ ...schema, type: nonNull[0] }, context)}?`;
  }
  switch (schema.type) {
    case "string":
      return "String";
    case "integer":
      return "Int";
    case "number":
      return "Double";
    case "boolean":
      return "Bool";
    case "array":
      if (!schema.items) throw new Error(`array without items at ${context}`);
      return `[${swiftType(schema.items, context)}]`;
    case "object": {
      const name = namedModel(schema);
      if (!name) throw new Error(`anonymous object at ${context}`);
      return name;
    }
    default:
      throw new Error(`unsupported type ${schema.type} at ${context}`);
  }
}

function renderStruct(name: string, schema: JsonSchema): string {
  if (schema.type !== "object" || !schema.properties) {
    throw new Error(`model ${name} is not an object`);
  }
  const required = new Set(schema.required ?? []);
  const conformances = ["Codable", "Equatable", "Hashable", "Sendable"];
  if ("id" in schema.properties) conformances.splice(1, 0, "Identifiable");
  const lines = [`struct ${name}: ${conformances.join(", ")} {`];
  for (const [prop, propSchema] of Object.entries(schema.properties)) {
    let type = swiftType(propSchema, `${name}.${prop}`);
    if (!required.has(prop) && !type.endsWith("?")) type += "?";
    lines.push(`    let ${prop}: ${type}`);
  }
  lines.push("}");
  return lines.join("\n");
}

const header = `// Generated by packages/protocol/scripts/codegen-swift.ts — DO NOT EDIT.
// 真源:packages/protocol/src/models.ts(zod)。改协议后运行 pnpm codegen:swift。

import Foundation
`;

const body = Object.entries(jsonSchemas)
  .map(([name, schema]) => renderStruct(name, schema))
  .join("\n\n");

const here = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.resolve(
  here,
  "../../../apps/desktop-macos/Sources/Generated/ProtocolModels.swift",
);
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${header}\n${body}\n`);
console.log(`wrote ${outPath}`);
